_select_data:
  aspect-ratio:
    - square
    - portrait
    - portrait-tall
    - landscape
    - landscape-wide

  column-sizes:
    col-6: One Half
    col-12: Full Width 
    col-4: One Third
    col-3: One Quarter
    col-6_sm-12: One Half (stacked mob.)
    col-4_sm12: One Third (stacked mob.)
    col-3_sm12: One Quarter (stacked mob.)